/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.comisariaorm.Vista;

import com.mycompany.comisariaorm.Modelo.Matricula;
import com.mycompany.comisariaorm.Modelo.Sospechoso;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import ConsultasH2.ConsultaSospechoso;
import com.mycompany.comisariaorm.Controlador.Controlador;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;


/**
 *
 * @author Your Name <Antonio Martinez Diaz>
 */
public class Tabla extends javax.swing.JFrame implements MouseListener, TableModelListener{

    /**
     * Creates new form Tabla
     */
    private ModeloTabla modelo;//
    private ArrayList<String> titulosList;
    private int filasTabla;
    private int columnasTabla;
    
    public Tabla() {

        initComponents();
       	construirTabla();
        Tsospechosos.addMouseListener(this);
        Tsospechosos.getModel().addTableModelListener(this);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tsospechosos = new javax.swing.JTable();
        TituloTablaSospechosos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tsospechosos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tsospechosos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        TituloTablaSospechosos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloTablaSospechosos.setText("Tabla  Sospechosos");

        jButton1.setText("Nuevo sospechoso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(TituloTablaSospechosos, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(TituloTablaSospechosos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          Object fila [] = new Object[titulosList.size()];
   
        
        modelo.addRow(fila);
        
        JDialog frame = new JDialog(this,"Insertar", true);
        Insertar i = new Insertar();
        frame.getContentPane().add(i);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
	
    private void construirTabla() {
	        titulosList=new ArrayList<>();
                titulosList.add("Id");
		titulosList.add("Nombre");
                titulosList.add("Apellidos");
                titulosList.add("Documentos");
                titulosList.add("Matriculas");
                titulosList.add("Domicilios");
                titulosList.add("Telefonos");
                titulosList.add("");
                titulosList.add("");
                
		//se asignan las columnas al arreglo para enviarse al momento de construir la tabla
		String titulos[] = new String[titulosList.size()];
		for (int i = 0; i < titulos.length; i++) {
			titulos[i]=titulosList.get(i);
		}
		
		Object[][] data =obtenerMatrizDatos(titulosList);
		construirTabla(titulos,data);
	}
    
    
	private Object[][] obtenerMatrizDatos(ArrayList<String> titulosList) {
		String informacion[][] = new String[Controlador.devolverSospechosos().size()][titulosList.size()];
		
		for (int x = 0; x < informacion.length; x++) {
                
                    long id = Controlador.idSospechoso(x);
                    informacion[x][Utilidades.ID] = Controlador.obtenerCampoMo("id", x) ;
                    informacion[x][Utilidades.NOMBRE] = Controlador.obtenerCampoMo("nombre", x) + "";
                    informacion[x][Utilidades.APELLIDOS] = Controlador.obtenerCampoMo("apellidos", x) + "";
                    informacion[x][Utilidades.DOCUMENTO] = Controlador.obtenerCampoMo("documento", x) + "";
                    informacion[x][Utilidades.MATRICULAS] = Controlador.obtenerCampoMul("matriculas", id);
                    informacion[x][Utilidades.DOMICILIOS] = Controlador.obtenerCampoMul("domicilios", id);
                    informacion[x][Utilidades.TELEFONOS] = Controlador.obtenerCampoMul("telefonos", id);;
                    informacion[x][Utilidades.PERFIL] = "PERFIL";
	            informacion[x][Utilidades.EVENTO] = "EVENTO";
                }
		return informacion;
	}
	

	private void construirTabla(String[] titulos, Object[][] data) {
		modelo=new ModeloTabla(data, titulos);
		//se asigna el modelo a la tabla
		Tsospechosos.setModel(modelo);
		
		filasTabla=Tsospechosos.getRowCount();
		columnasTabla=Tsospechosos.getColumnCount();
		
		Tsospechosos.getColumnModel().getColumn(Utilidades.PERFIL).setCellRenderer(new GestionCeldas("icono"));
		Tsospechosos.getColumnModel().getColumn(Utilidades.EVENTO).setCellRenderer(new GestionCeldas("icono"));
		Tsospechosos.getColumnModel().getColumn(Utilidades.PERFIL).setPreferredWidth(10);
		Tsospechosos.getColumnModel().getColumn(Utilidades.EVENTO).setPreferredWidth(10);
		


	}

	@Override
	public void mouseClicked(MouseEvent e) {
		int fila = Tsospechosos.rowAtPoint(e.getPoint());
		int columna = Tsospechosos.columnAtPoint(e.getPoint());
	
	
		if (columna==Utilidades.PERFIL) {
			validarSeleccionMouse(fila);      
		}else if (columna==Utilidades.EVENTO){
		   JOptionPane.showMessageDialog(null, "Evento del otro icono");
		}
		
	}

	private void validarSeleccionMouse(int fila) {
		Utilidades.filaSeleccionada=fila;
		String info="INFO PERSONA\n";
		info+="Documento:"+"\n";
		info+="Nombre: "+"\n";
		
		JOptionPane.showMessageDialog(null, info);
	}

	
        
        
        

	@Override
	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mousePressed(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void mouseReleased(MouseEvent arg0) {
		// TODO Auto-generated method stub
		
	}

    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabla().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    
    
    
    
    
 
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloTablaSospechosos;
    private javax.swing.JTable Tsospechosos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableChanged(TableModelEvent e) {
       
        System.out.println( modelo.getValueAt(e.getFirstRow(), 0));   
        System.out.println(  modelo.getColumnCount());
        
     
      
        
    }
}
